name: Update image

on:
  push:
    branches:
    - main
    paths:
    - 'Dockerfile'
  repository_dispatch:
    types: [update-image]


jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: update-remote
        run: ./image-update/update-remote-image.sh
